### ISSUE TITLE
json file

### ISSUE THREAD

**Issue by emi-marfe** [martinraj/MVVM-architecture-lifecycle-components-and-Room-database-project#1]
hello sir ..is there a hope for me to get the json file so has to import it in my firebase database too??

**Comment by worldamaa** [comment]
I also need json file plz

**Comment by martinraj** [comment]
**JSON string:**
[{"average_rating":3.5,"image_url":"https://cdn.pixabay.com/photo/2014/09/18/21/17/sandwich-451403_640.jpg","item_name":"Sandwich","item_price":80},{"average_rating":4,"image_url":"https://cdn.pixabay.com/photo/2015/05/11/11/46/fried-rice-762362_640.jpg","item_name":"Fried Rice","item_price":110},{"average_rating":4.2,"image_url":"https://cdn.pixabay.com/photo/2015/04/20/13/25/burger-731298_640.jpg","item_name":"Burger","item_price":125.5},{"average_rating":3.8,"image_url":"https://cdn.pixabay.com/photo/2014/11/05/16/00/thai-food-518035_640.jpg","item_name":"Noodles","item_price":132.5},{"average_rating":4.2,"image_url":"https://cdn.pixabay.com/photo/2017/01/03/11/33/pizza-1949183_640.jpg","item_name":"Pizza","item_price":180},{"average_rating":4.8,"image_url":"https://cdn.pixabay.com/photo/2015/08/11/10/34/camel-meat-883772_640.jpg","item_name":"Biryani","item_price":210}]

**Comment by martinraj** [comment]
> I also need json file plz

**JSON string:**
[{"average_rating":3.5,"image_url":"https://cdn.pixabay.com/photo/2014/09/18/21/17/sandwich-451403_640.jpg","item_name":"Sandwich","item_price":80},{"average_rating":4,"image_url":"https://cdn.pixabay.com/photo/2015/05/11/11/46/fried-rice-762362_640.jpg","item_name":"Fried Rice","item_price":110},{"average_rating":4.2,"image_url":"https://cdn.pixabay.com/photo/2015/04/20/13/25/burger-731298_640.jpg","item_name":"Burger","item_price":125.5},{"average_rating":3.8,"image_url":"https://cdn.pixabay.com/photo/2014/11/05/16/00/thai-food-518035_640.jpg","item_name":"Noodles","item_price":132.5},{"average_rating":4.2,"image_url":"https://cdn.pixabay.com/photo/2017/01/03/11/33/pizza-1949183_640.jpg","item_name":"Pizza","item_price":180},{"average_rating":4.8,"image_url":"https://cdn.pixabay.com/photo/2015/08/11/10/34/camel-meat-883772_640.jpg","item_name":"Biryani","item_price":210}]
